name: Good Dog Service Release

on:
 push:
   branches: [ $default-branch ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 12 # Match github-script node version
      - run: npm install date-fns@^2.28.0
      - id: tag-release
        uses: actions/github-script@v5
        with:
          script: |
            const { formatRFC3339 } = require('date-fns')

            const nextVersion = formatRFC3339(new Date).replace(/:/g, '-');

            await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: nextVersion,
              name: nextVersion,
              target_commitish: context.sha
            });
            core.setOutput('release_version', nextVersion);
      - id: start-codepipeline
        run: |
          aws codepipeline start-pipeline-execution --name [PIPELINE NAME]
